namespace: adp-demo
subscriptionId: 00000000-0000-0000-0000-000000000000
azrMSTPrivateLinkDNSSubscriptionID: 00000000-0000-0000-0000-000000000000
teamResourceGroupName: adp-demo-team-rg
azrMSTPrivateLinkDNSUKSouthResourceGroupName: adp-demo-dns-rg-uks
azrMSTPrivateLinkDNSUKWestResourceGroupName: adp-demo-dns-rg-ukw
virtualNetworkResourceGroupName: adp-demo-net-rg
serviceBusResourceGroupName: adp-demo-rg
storageAccountPrefix: adp-demo-sa
serviceBusNamespaceName: adp-demo-ns
virtualNetworkName: adp-demo-net
privateEndpointSubnetName: adp-demo-sub-net
privateEndpointPrefix: adp-demo-pe
teamMIPrefix: adp-mi
serviceName: adp-demo-app
fluxConfigNamespace: flux-config
environment: env1
enablePrivateEndpoint: enable
namespaceQueues:
  - name: demo-queue
    roleAssignments:
      - roleName: 'QueueSender'
namespaceTopics:
  - name: demo-topic
    roleAssignments:
      - roleName: 'TopicSender'
storageAccounts:
  - name: storage01
    roleAssignments:
      - roleName: 'DataReader'
      - roleName: 'DataWriter'
    storageAccountsFileService:
      deleteRetentionPolicy:
        enabled: false
        days: 15
    blobContainers:
      - name: container-01
    tables:
      - name: table01
    fileShares:
      - name: share-01
      - name: share-02
        accessTier: Hot
        shareQuota: 50