name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: gg/250126-GitPublish-template

extends:
  template: /pipelines/common-helm-library-publish.yaml@DEFRA-ADPPipelineCommon
  parameters:
    helmLibraryName: 'adp-aso-helm-library'
    helmRepositoryConfig:
      name: 'defra-adp-sandpit/adp-aso-helm-repository'
      endpoint: 'defra-adp-sandpit'
      chartRepoPublicUrl: "https://raw.githubusercontent.com/defra/adp-helm-repository/gg/asorepo/" 