{{- define "adp-aso-helm-library.federated-credential" -}}
{{- range $federatedCred := $.Values.userAssignedIdentity.federatedCreds }}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  {{- $namespaceName := required (printf $requiredMsg "userAssignedIdentity.federatedCred.namespace") $federatedCred.namespace }}
  {{- $serviceAccountName := required (printf $requiredMsg "userAssignedIdentity.federatedCred.serviceAccountName") $federatedCred.serviceAccountName }}
  {{- $managedIdName := (required (printf $requiredMsg "userAssignedIdentity.managedIdName") $.Values.userAssignedIdentity.managedIdName) | lower }}
  name: {{ $managedIdName }}-fic
  namespace: {{ $namespaceName }}
spec:
  owner:
    name: {{ $managedIdName }}
  audiences:
    - api://AzureADTokenExchange
  issuer: {{ required (printf $requiredMsg "clusterOIDCIssuerUrl") $.Values.clusterOIDCIssuerUrl }}
  subject: {{ (printf "system:serviceaccount:%s:%s" $namespaceName $serviceAccountName) | lower }}
---  
{{- end }}   
{{- end }}