{{- define "adp-aso-helm-library.federated-credential" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  {{- $namespaceName := required (printf $requiredMsg "namespace") $.Values.namespace }}
  {{- $serviceAccountName := required (printf $requiredMsg "userAssignedIdentity.federatedCred.serviceAccountName") $.Values.userAssignedIdentity.federatedCred.serviceAccountName }}
  {{- $managedIdPrefix := (required (printf $requiredMsg "managedIdPrefix") $.Values.managedIdPrefix) | lower }}
  {{- $managedIdSuffix := (required (printf $requiredMsg "userAssignedIdentity.managedIdName") $.Values.userAssignedIdentity.managedIdName) | lower }}
  {{- $managedIdName :=  printf "%s-%s" $managedIdPrefix $managedIdSuffix }}
  name: {{ $managedIdName }}-fic
  namespace: {{ $namespaceName }}
spec:
  owner:
    name: {{ $managedIdName }}
  audiences:
    - api://AzureADTokenExchange
  issuer: {{ required (printf $requiredMsg "Cluster_OIDC") $.Values.Cluster_OIDC }}
  subject: {{ (printf "system:serviceaccount:%s:%s" $namespaceName $serviceAccountName) | lower }}
{{- end }}