{{- define "adp-aso-helm-library.namespace-topic-subscription" -}}
{{- $ := index . 0 }}
{{- $arg := index . 1 }}
{{- range $namespaceTopicSubscription := $arg.topicSubscriptions }}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: servicebus.azure.com/v1api20211101
kind: NamespacesTopicsSubscription
metadata:
  name: {{ required (printf $requiredMsg "namespaceTopicSubscription.name") $namespaceTopicSubscription.name }}
  namespace: {{ required (printf $requiredMsg "namespace") $.Values.namespace | quote }}  
  {{- with $.Values.asoAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  azureName: {{ required (printf $requiredMsg "namespaceTopicSubscription.name") $namespaceTopicSubscription.name }}
  deadLetteringOnFilterEvaluationExceptions: {{ $namespaceTopicSubscription.deadLetteringOnFilterEvaluationExceptions | default false }}
  deadLetteringOnMessageExpiration: {{ $namespaceTopicSubscription.deadLetteringOnMessageExpiration | default false }}
  defaultMessageTimeToLive: {{ $namespaceTopicSubscription.defaultMessageTimeToLive | default "P14D" | quote }}
  duplicateDetectionHistoryTimeWindow: {{ $namespaceTopicSubscription.duplicateDetectionHistoryTimeWindow | default "PT10M" | quote }}  
  enableBatchedOperations: {{ $namespaceTopicSubscription.enableBatchedOperations | default true }}
  {{- if $namespaceTopicSubscription.forwardTo }}
  forwardTo: {{ $namespaceTopicSubscription.forwardTo }}
  {{- end }}
  # forwardDeadLetteredMessagesTo: {{ $namespaceTopicSubscription.forwardDeadLetteredMessagesTo | default "" }}
  isClientAffine: {{ $namespaceTopicSubscription.isClientAffine | default false }}
  lockDuration: {{ $namespaceTopicSubscription.lockDuration | default "PT1M" | quote }} 
  maxDeliveryCount: {{ $namespaceTopicSubscription.maxDeliveryCount | default 10 }} 
  requiresSession: {{ $namespaceTopicSubscription.requiresSession | default false }}
  {{- $subscriptionId := required (printf $requiredMsg "subscriptionId") $.Values.subscriptionId }}
  {{- $serviceBusResourceGroupName := required (printf $requiredMsg "serviceBusResourceGroupName") $.Values.serviceBusResourceGroupName }}
  {{- $serviceBusNamespaceName := required (printf $requiredMsg "serviceBusNamespaceName") $.Values.serviceBusNamespaceName }}
  {{- $serviceBusTopicName := printf "%s-%s" $.Values.namespace $arg.name }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.ServiceBus/namespaces/%s/topics/%s" $subscriptionId $serviceBusResourceGroupName $serviceBusNamespaceName $serviceBusTopicName }}                       
---  
{{- end }}
{{- end }}