{{- define "adp-aso-helm-library.namespace-topic" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- range $namespaceTopic := .Values.namespaceTopics }}
{{- $owner := $namespaceTopic.owner | default "yes" }}
{{- $topicName := include "resource.fullname" (list $ (required (printf $requiredMsg "namespaceTopic.name") $namespaceTopic.name)) }}
{{- if eq $owner "yes" }}
apiVersion: servicebus.azure.com/v1api20211101
kind: NamespacesTopic
metadata:
  name: {{ $topicName }}
  namespace: {{ required (printf $requiredMsg "namespace") $.Values.namespace | quote }}  
  {{- with $.Values.asoAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  azureName: {{ $topicName }}
  defaultMessageTimeToLive: {{ $namespaceTopic.defaultMessageTimeToLive | default "P14D" | quote }} 
  duplicateDetectionHistoryTimeWindow: {{ $namespaceTopic.duplicateDetectionHistoryTimeWindow | default "PT10M" | quote }}  
  enableBatchedOperations: {{ $namespaceTopic.enableBatchedOperations | default true }}
  enableExpress: {{ $namespaceTopic.enableExpress | default false }}
  enablePartitioning: {{ $namespaceTopic.enablePartitioning | default false }}
  maxMessageSizeInKilobytes: {{ $namespaceTopic.maxMessageSizeInKilobytes | default 1024 }} 
  maxSizeInMegabytes: {{ $namespaceTopic.maxSizeInMegabytes | default 1024 }} 
  requiresDuplicateDetection: {{ $namespaceTopic.requiresDuplicateDetection | default false }}
  supportOrdering: {{ $namespaceTopic.supportOrdering | default true }}
  {{- $subscriptionId := required (printf $requiredMsg "subscriptionId") $.Values.subscriptionId }}
  {{- $serviceBusResourceGroupName := required (printf $requiredMsg "serviceBusResourceGroupName") $.Values.serviceBusResourceGroupName }}
  {{- $serviceBusNamespaceName := required (printf $requiredMsg "serviceBusNamespaceName") $.Values.serviceBusNamespaceName }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.ServiceBus/namespaces/%s" $subscriptionId $serviceBusResourceGroupName $serviceBusNamespaceName }}  
---     
{{- end }}
{{- if $namespaceTopic.topicSubscriptions }}    
{{- include "adp-aso-helm-library.namespace-topic-subscription" (list $ .) }}   
{{- end }} 
{{- if $namespaceTopic.roleAssignments }}    
{{- include "adp-aso-helm-library.role-assignment-managed" (list $ $namespaceTopic.roleAssignments $topicName "namespaceTopic") }}   
{{- end }} 
{{- end }}
{{- end }}