{{- define "adp-aso-helm-library.private-dns-zone-a-record" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- $subscriptionId := required (printf $requiredMsg "subscriptionId") .Values.subscriptionId }} 
{{- $environment := required (printf $requiredMsg "environment") $.Values.environment | lower }} 
{{- $fluxConfigNamespace := required (printf $requiredMsg "fluxConfigNamespace") $.Values.fluxConfigNamespace }}
{{- $storageAccounts := required (printf $requiredMsg "storageAccounts") .Values.storageAccounts }}
{{- range $storageAccountObj := .Values.storageAccounts }}
{{- $storageAccountName :=  required (printf $requiredMsg "storageAccount[].name") $storageAccountObj.name }}
{{- $storageAccountFullName :=  include "storageAccount.fullname" (list $ $storageAccountName) }}
{{- $owner := $storageAccountObj.owner | default "yes" }}
{{- if eq $owner "yes" }}
{{- $privateEndpointBlobName :=  include "privateEndpoint.name" (list $ $storageAccountFullName "blob") }}
apiVersion: network.azure.com/v1api20200601
kind: PrivateDnsZonesARecord
metadata:
  name: {{ printf "privatelink.blob.core.windows.net-%s" $storageAccountFullName }}
  namespace: {{ required (printf $requiredMsg "fluxConfigNamespace") $.Values.fluxConfigNamespace }}
  labels:
    privateEndpointBlobName: {{ $privateEndpointBlobName }}
spec:
  aRecords:
  {{- if (lookup "network.azure.com/v1api20220701" "PrivateEndpoint" "flux-config" $privateEndpointBlobName) }}
  - ipv4Address: {{ (index (index (lookup "network.azure.com/v1api20220701" "PrivateEndpoint" "flux-config" $privateEndpointBlobName).status.customDnsConfigs 0).ipAddresses 0) }}
  {{- end }} 
  azureName: {{ $storageAccountFullName }}
  owner:
    {{- if eq ($storageAccountObj.location | default "uksouth") "uksouth"}}
    armId: {{ include "privateDNSZone.resourceId" (list $ ($environment) "privatelink.blob.core.windows.net" "ukwest") }}  
    {{- else }}
    armId: {{ include "privateDNSZone.resourceId" (list $ ($environment) "privatelink.blob.core.windows.net" "uksouth") }}  
    {{- end }}
  ttl: 3600   
---
{{- $privateEndpointTableName :=  include "privateEndpoint.name" (list $ $storageAccountFullName "table") }}
apiVersion: network.azure.com/v1api20200601
kind: PrivateDnsZonesARecord
metadata:
  name: {{ printf "privatelink.table.core.windows.net-%s" $storageAccountFullName }}
  namespace: {{ required (printf $requiredMsg "fluxConfigNamespace") $.Values.fluxConfigNamespace }}
  labels:
    privateEndpointTableName: {{ $privateEndpointTableName }}
spec:
  aRecords:
  {{- if (lookup "network.azure.com/v1api20220701" "PrivateEndpoint" "flux-config" $privateEndpointTableName) }}
  - ipv4Address: {{ (index (index (lookup "network.azure.com/v1api20220701" "PrivateEndpoint" "flux-config" $privateEndpointTableName).status.customDnsConfigs 0).ipAddresses 0) }}
  {{- end }} 
  azureName: {{ $storageAccountFullName }}
  owner:
    {{- if eq ($storageAccountObj.location | default "uksouth") "uksouth"}}
    armId: {{ include "privateDNSZone.resourceId" (list $ ($environment) "privatelink.table.core.windows.net" "ukwest") }}  
    {{- else }}
    armId: {{ include "privateDNSZone.resourceId" (list $ ($environment) "privatelink.table.core.windows.net" "uksouth") }}  
    {{- end }}
  ttl: 3600   
{{- end }} 
{{- end }}  
{{- end }} 