{{- define "adp-aso-helm-library.service-account" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- $managedIdConfigMapName :=  include "managedidentity.configMapName" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required (printf $requiredMsg "serviceName") .Values.serviceName }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace }}
  labels:
    toolkit.fluxcd.io/tenant: {{ required (printf $requiredMsg "teamName") .Values.teamName }}
  annotations:
    {{- $configmap := (lookup "v1" "ConfigMap" .Values.namespace $managedIdConfigMapName) }}
    {{- if $configmap }}
    {{- $clientId := get $configmap.data "clientId" }}
    azure.workload.identity/client-id: {{ $clientId }}
    {{ else }}
    azure.workload.identity/client-id: ''
    {{- end }} 
{{- end }}