{{- define "adp-aso-helm-library.storage-account" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- $teamRGName := required (printf $requiredMsg "teamResourceGroupName") .Values.teamResourceGroupName }}
{{- $subscriptionId := required (printf $requiredMsg "subscriptionId") .Values.subscriptionId }} 
{{- $environment := required (printf $requiredMsg "environment") $.Values.environment | lower }} 
{{- $storageAccountObject := required (printf $requiredMsg "storageAccounts") .Values.storageAccounts }}
{{- range $storageAccount := .Values.storageAccounts }}
{{- $storageAccountName :=  required (printf $requiredMsg "storageAccount[].name") $storageAccount.name }}
{{- $storageAccountFullName :=  include "storageAccount.fullname" (list $ $storageAccountName) }}
{{- $owner := $storageAccount.owner | default "yes" }}

{{- if eq $owner "yes" }}
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccount
metadata:
  name: {{ include "storageAccount.metadata.fullname" (list $ $storageAccountFullName) }}
  namespace: {{ required (printf $requiredMsg "namespace") $.Values.namespace | quote }}  
  {{- with $.Values.asoAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  azureName: {{ $storageAccountFullName }}
  accessTier: {{ $storageAccount.accessTier | default "Hot" }}
  kind: StorageV2
  sku:
    name: "Standard_LRS"
    tier: Standard
  location: {{ $storageAccount.location | default "uksouth" | quote }}
  allowBlobPublicAccess: false
  allowCrossTenantReplication: {{ $storageAccount.allowCrossTenantReplication | default false }}
  allowSharedKeyAccess: {{ $storageAccount.allowSharedKeyAccess | default false }}
  defaultToOAuthAuthentication: {{ $storageAccount.defaultToOAuthAuthentication | default true }}
  dnsEndpointType: "Standard"
  encryption:
    keySource: Microsoft.Storage
    requireInfrastructureEncryption: true
    services:
      blob:
        enabled: true
        keyType: Account
      file:
        enabled: true
        keyType: Account
  minimumTlsVersion: "TLS1_2"
  networkAcls:
    bypass: AzureServices
    defaultAction: Deny
    {{- if and $storageAccount.networkAcls $storageAccount.networkAcls.ipRules }}
    ipRules: 
    {{- range $storageAccount.networkAcls.ipRules }}
    - action: Allow
      value: {{ . }}
    {{- end }} 
    {{- end }}    
  {{- if and $storageAccount.networkAcls $storageAccount.networkAcls.ipRules }}  
  publicNetworkAccess: "Enabled" 
  {{- else }} 
  publicNetworkAccess: "Disabled"
  {{- end }} 
  supportsHttpsTrafficOnly: true
  tags:
  {{- include "adp-aso-helm-library.commonTags" (list $ "") | indent 4 }} 
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s" $subscriptionId $teamRGName }}  
---
{{- include "adp-aso-helm-library.storage-account-private-endpoint" (list $ $storageAccount $storageAccountFullName "blob") }} 
---
{{- include "adp-aso-helm-library.storage-account-private-endpoint" (list $ $storageAccount $storageAccountFullName "table") }}
{{- end }} 
---  
{{- include "adp-aso-helm-library.storage-account-blob-service" (list $ .) }} 
--- 
{{- if $storageAccount.blobContainers }}  
---  
{{- include "adp-aso-helm-library.storage-account-blob-services-container" (list $ .) }} 
{{- end }} 
{{- if $storageAccount.tables }}  
---  
{{- include "adp-aso-helm-library.storage-account-table-services-table" (list $ .) }}  
{{- end }} 
{{- end }}
{{- end }}