{{- define "adp-aso-helm-library.storage-account-table-services-table" -}}
{{- $ := index . 0 }}
{{- $storageAccountObj := index . 1 }}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- $storageAccountFullName := include "storageAccount.fullname" (list $ $storageAccountObj.name) }}
{{- range $storageAccountsTableServicesTable := $storageAccountObj.tables }}
{{- if $storageAccountsTableServicesTable.roleAssignments }} 
{{- fail (printf "RoleAssignments at the Table scope is now deprecated. Please set roleAssignments at the storage account level and reference version ^2.0.0 of the adp-aso-helm-library in the chart.yaml file.") }} 
{{- end }}
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsTableServicesTable
metadata:
  name: {{ include "storageAccountsTableServicesTable.metadata.fullname" (list $ $storageAccountFullName $storageAccountsTableServicesTable.name) }}
  namespace: {{ required (printf $requiredMsg "namespace") $.Values.namespace | quote }}  
  {{- with $.Values.asoAnnotations }}
  annotations: 
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  azureName: {{ $storageAccountsTableServicesTable.name }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Storage/storageAccounts/%s/tableServices/default" $.Values.subscriptionId $.Values.teamResourceGroupName $storageAccountFullName }} 
---
{{- end }}
{{- end }}