{{- define "adp-aso-helm-library.storage-account-blob-services-container" -}}
{{- $ := index . 0 }}
{{- $storageAccountObj := index . 1 }}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
{{- $storageAccountFullName := include "storageAccount.fullname" (list $ $storageAccountObj.name) }}
{{- range $storageAccountsBlobServicesContainer := $storageAccountObj.blobContainers }}
{{- if $storageAccountsBlobServicesContainer.roleAssignments }} 
{{- fail (printf "RoleAssignments at the Container scope is now deprecated. Please set roleAssignments at the storage account level and reference version ^2.0.0 of the adp-aso-helm-library in the chart.yaml file.") }} 
{{- end }}
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsBlobServicesContainer
metadata:
  name: {{ include "storageAccountsBlobServicesContainer.metadata.fullname" (list $ $storageAccountFullName $storageAccountsBlobServicesContainer.name) }}
  namespace: {{ required (printf $requiredMsg "namespace") $.Values.namespace | quote }}  
  {{- with $.Values.asoAnnotations }}
  annotations:
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  azureName: {{ $storageAccountsBlobServicesContainer.name }}
  publicAccess: {{ $storageAccountsBlobServicesContainer.publicAccess | default "None" }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Storage/storageAccounts/%s/blobServices/default" $.Values.subscriptionId $.Values.teamResourceGroupName $storageAccountFullName }} 
--- 
{{- end }}
{{- end }}