{{- define "adp-aso-helm-library.userassignedidentity" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  {{- $managedIdName := required (printf $requiredMsg "userAssignedIdentity.managedIdName") .Values.userAssignedIdentity.managedIdName | lower }}
  {{- $managedIdConfigMapName :=  printf "%s-mi-identity-settings" $managedIdName }}
  {{- $teamRGName := required (printf $requiredMsg "teamResourceGroupName") .Values.teamResourceGroupName }}
  name: {{ $managedIdName }}
  {{- if .Values.fluxConfigNamespace }}
  namespace: {{ .Values.fluxConfigNamespace }}
  {{- else }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace }}
  {{- end }}
  {{- with .Values.asoAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  azureName: {{ $managedIdName }}
  location: {{ .Values.userAssignedIdentity.location | default "uksouth" | quote }}
  operatorSpec:
    configMaps:
      principalId:
        name: {{ $managedIdConfigMapName }} 
        key: principalId
      clientId:
        name: {{ $managedIdConfigMapName }} 
        key: clientId   
      tenantId:
        name: {{ $managedIdConfigMapName }} 
        key: tenantId    
  tags: 
  {{- include "adp-aso-helm-library.tags" . | indent  4 }}      
  {{- $subscriptionId := required (printf $requiredMsg "subscriptionId") .Values.subscriptionId }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s" $subscriptionId $teamRGName }}

{{- if .Values.userAssignedIdentity.federatedCreds }}    
--- 
{{- include "adp-aso-helm-library.federated-credential" $ }}   
{{- end }} 

{{- if .Values.userAssignedIdentity.roleAssignments }}    
---
{{- include "adp-aso-helm-library.role-assignment" $ }}   
{{- end }}     
{{- end }}
