{{- define "adp-aso-helm-library.userassignedidentity" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  {{- $managedIdName := include "managedidentity.name" . }}
  {{- $managedIdConfigMapName :=  include "managedidentity.configMapName" . }}
  {{- $teamRGName := required (printf $requiredMsg "teamResourceGroupName") .Values.teamResourceGroupName }}
  {{- $userAssignedIdentityObject := required (printf $requiredMsg "userAssignedIdentity") .Values.userAssignedIdentity }}
  {{- $commonTags := required (printf $requiredMsg "commonTags") .Values.commonTags }}
  name: {{ $managedIdName }}
  namespace: {{ required (printf $requiredMsg "fluxConfigNamespace") .Values.fluxConfigNamespace }}
  {{- with .Values.asoAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  azureName: {{ $managedIdName }}
  {{- if and .Values.userAssignedIdentity .Values.userAssignedIdentity.location }} 
  location: {{ .Values.userAssignedIdentity.location | quote }}
  {{- else }}
  location: "uksouth"
  {{- end }}
  operatorSpec:
    configMaps:
      principalId:
        name: {{ $managedIdConfigMapName }} 
        key: principalId
      clientId:
        name: {{ $managedIdConfigMapName }} 
        key: clientId   
      tenantId:
        name: {{ $managedIdConfigMapName }} 
        key: tenantId    
  tags: 
  {{- include "adp-aso-helm-library.commonTags" (list . "") | indent 4 }} 
  {{- $subscriptionId := required (printf $requiredMsg "subscriptionId") .Values.subscriptionId }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s" $subscriptionId $teamRGName }}

{{- if and .Values.userAssignedIdentity .Values.userAssignedIdentity.federatedCreds }}    
--- 
{{- include "adp-aso-helm-library.federated-credential" $ }}   
{{- end }}    

{{- end }}
