{{- define "adp-aso-helm-library.workload-identity" -}}
{{- $requiredMsg := include "adp-aso-helm-library.default-check-required-msg" . }}
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  {{- $managedIdName := include "managedidentity.name" . }}
  {{- $managedIdConfigMapName :=  include "managedidentity.configMapName" . }}
  {{- $teamRGName := required (printf $requiredMsg "teamResourceGroupName") .Values.teamResourceGroupName }}
  {{- $workloadIdentityObject := required (printf $requiredMsg "workloadIdentity") .Values.workloadIdentity }}
  {{- $commontags := required (printf $requiredMsg "commontags") .Values.commontags }}
  name: {{ $managedIdName }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace }}
  {{- with .Values.asoAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  azureName: {{ $managedIdName }}
  {{- if and .Values.workloadIdentity .Values.workloadIdentity.location }} 
  location: {{ .Values.workloadIdentity.location | quote }}
  {{- else }}
  location: "uksouth"
  {{- end }}
  operatorSpec:
    configMaps:
      principalId:
        name: {{ $managedIdConfigMapName }} 
        key: principalId
      clientId:
        name: {{ $managedIdConfigMapName }} 
        key: clientId   
      tenantId:
        name: {{ $managedIdConfigMapName }} 
        key: tenantId    
  tags: 
  {{- include "adp-aso-helm-library.commontags" (list . "") | indent 4 }} 
  {{- $subscriptionId := required (printf $requiredMsg "subscriptionId") .Values.subscriptionId }}
  owner:
    armId: {{ printf "/subscriptions/%s/resourceGroups/%s" $subscriptionId $teamRGName }}

---
{{- include "adp-aso-helm-library.service-account" . }}   

{{- if and .Values.workloadIdentity .Values.workloadIdentity.federatedCreds }}    
--- 
{{- include "adp-aso-helm-library.federated-credential" $ }}   
{{- end }}    

{{- end }}
